#!/usr/bin/env python3
"""
CLI generator for Minecraft servers.
"""

import os
from pathlib import Path
from typing import Dict, Any

def generate_launch_script(server: Dict[str, Any]) -> str:
    """Generate a shell script to launch a Minecraft server."""
    server_type = server.get("server_type", "java")
    jar_path = server.get("jar_path", "./server.jar")
    version = server.get("version", "1.20.1")
    name = server.get("name", "server")
    
    if server_type == "java":
        script = f"""#!/bin/bash
# Minecraft Java Server Launch Script
# Server: {name} (v{version})
# Generated by Minecraft Server Manager

SERVER_JAR="{jar_path}"
JAVA_OPTS="-Xmx2G -Xms1G -Dterminal.jline=false -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+ExplicitGCInvokesConcurrent"

java ${{JAVA_OPTS}} -jar "${{SERVER_JAR}}" nogui
"""
    else:
        script = f"""#!/bin/bash
# Minecraft Bedrock Server Launch Script
# Server: {name} (v{version})
# Generated by Minecraft Server Manager

SERVER_BINARY="{jar_path}"
ulimit -n 8192

php ${{SERVER_BINARY}}
"""
    
    return script

def save_script(script: str, filename: str) -> str:
    """Save script to file and return the path."""
    output_path = Path("generated_scripts") / filename
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_text(script)
    return str(output_path)
