"""
Minecraft server.properties management.
"""

import os
import re
from pathlib import Path
from typing import Any, Dict, Optional
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ServerProperties:
    """Manage server.properties files."""
    
    DEFAULT_PORT = 25565
    DEFAULT_MAX_PLAYERS = 20
    DEFAULT_VIEW_DISTANCE = 10
    DEFAULT_LEVEL_NAME = "world"
    DEFAULT_GAMEMODE = "survival"
    DEFAULT_DIFFICULTY = "normal"
    DEFAULT_ONLINE_MODE = "true"
    
    def __init__(self, server_dir: str = "servers"):
        self.server_dir = Path(server_dir)
        self.properties_file = self.server_dir / "server.properties"
    
    def find_properties(self) -> Optional[Path]:
        """Find server.properties in server directory."""
        if self.properties_file.exists():
            return self.properties_file
        
        # Check subdirectories
        for prop in self.server_dir.glob("*/server.properties"):
            return prop
        return None
    
    def read(self) -> Dict[str, str]:
        """Read server.properties."""
        props = {}
        prop_file = self.find_properties()
        
        if not prop_file:
            logger.warning("No server.properties found")
            return self.get_defaults()
        
        with open(prop_file, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#"):
                    if "=" in line:
                        key, value = line.split("=", 1)
                        props[key.strip()] = value.strip()
        
        logger.info("Read %d properties from %s", len(props), prop_file)
        return props
    
    def write(self, properties: Dict[str, str], output_path: Optional[Path] = None) -> Path:
        """Write server.properties."""
        if output_path is None:
            output_path = self.properties_file
        
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("# Minecraft Server Properties\n")
            f.write("# Generated by Minecraft Server Manager\n\n")
            
            for key, value in sorted(properties.items()):
                f.write(f"{key}={value}\n")
        
        logger.info("Wrote properties to %s", output_path)
        return output_path
    
    def get_defaults(self) -> Dict[str, str]:
        """Get default properties."""
        return {
            "server-port": str(self.DEFAULT_PORT),
            "server-ip": "",
            "max-players": str(self.DEFAULT_MAX_PLAYERS),
            "view-distance": str(self.DEFAULT_VIEW_DISTANCE),
            "level-name": self.DEFAULT_LEVEL_NAME,
            "gamemode": self.DEFAULT_GAMEMODE,
            "difficulty": self.DEFAULT_DIFFICULTY,
            "online-mode": self.DEFAULT_ONLINE_MODE,
            "white-list": "false",
            "enable-query": "false",
            "enable-rcon": "false",
            "rcon.port": "25575",
            "motd": "Minecraft Server",
        }
    
    def get_port(self) -> int:
        """Get server port."""
        props = self.read()
        return int(props.get("server-port", self.DEFAULT_PORT))
    
    def set_port(self, port: int) -> bool:
        """Set server port."""
        props = self.read()
        props["server-port"] = str(port)
        try:
            self.write(props)
            return True
        except Exception as e:
            logger.error("Failed to set port: %s", e)
            return False
    
    def get_max_players(self) -> int:
        """Get max players."""
        props = self.read()
        return int(props.get("max-players", self.DEFAULT_MAX_PLAYERS))
    
    def set_max_players(self, max_players: int) -> bool:
        """Set max players."""
        props = self.read()
        props["max-players"] = str(max_players)
        try:
            self.write(props)
            return True
        except Exception as e:
            logger.error("Failed to set max players: %s", e)
            return False
    
    def get_motd(self) -> str:
        """Get server MOTD."""
        props = self.read()
        return props.get("motd", "Minecraft Server")
    
    def set_motd(self, motd: str) -> bool:
        """Set server MOTD."""
        props = self.read()
        props["motd"] = motd
        try:
            self.write(props)
            return True
        except Exception as e:
            logger.error("Failed to set MOTD: %s", e)
            return False
    
    def get_gamemode(self) -> str:
        """Get gamemode."""
        props = self.read()
        return props.get("gamemode", self.DEFAULT_GAMEMODE)
    
    def set_gamemode(self, gamemode: str) -> bool:
        """Set gamemode."""
        valid_modes = ["survival", "creative", "adventure", "spectator"]
        if gamemode.lower() not in valid_modes:
            logger.error("Invalid gamemode: %s", gamemode)
            return False
        
        props = self.read()
        props["gamemode"] = gamemode.lower()
        try:
            self.write(props)
            return True
        except Exception as e:
            logger.error("Failed to set gamemode: %s", e)
            return False

    def get_difficulty(self) -> str:
        """Get difficulty."""
        props = self.read()
        return props.get("difficulty", self.DEFAULT_DIFFICULTY)

    def set_difficulty(self, difficulty: str) -> bool:
        """Set difficulty."""
        valid_difficulties = ["peaceful", "easy", "normal", "hard"]
        if difficulty.lower() not in valid_difficulties:
            logger.error("Invalid difficulty: %s", difficulty)
            return False

        props = self.read()
        props["difficulty"] = difficulty.lower()
        try:
            self.write(props)
            return True
        except Exception as e:
            logger.error("Failed to set difficulty: %s", e)
            return False